nsra/activity/urls.py
from django.urls import include, path
from .views import categorized_page

urlpatterns = [
    path('activity-data-views/<category>/<page>/', categorized_page, name='categorized_pages'),
    # <int:category>/<int:page>/
]

nsra/newsletter/urls.py
from birdsong import urls as birdsong_urls
from django.urls import include, path
from .views import subscribe

urlpatterns = [
    
    path('/', include(birdsong_urls)), 
    path('newsletter/subscribe/', subscribe, name='newsletter-subscribe'),
]

nsra/stats/urls.py
#from . views import index
from . import views

from django.urls import path

app_name = 'stats'

urlpatterns = [
    #path('', views.index, name="index_view"),
    path('', views.index, name='index'),

    path('NTF/', views.time, name='NTF'),
	path('time/series/index/', views.time_index, name='time_series'),
	path('chart/', views.chart, name='chart'),
	path('age_group/', views.age_group, name='age_group'),
	path('gender/', views.gender, name='gender'),
	path('FCE/', views.FCE, name='FCE'),
	path('UNF/', views.UNF, name='UNF'),
	path('UNC/', views.UNC, name='UNC'),
	path('vehicles/', views.vehicles, name='vehicles'),
	path('NTCC/', views.NTCC, name='NTCC'),

]

nsra/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from nsra.search import views as search_views
from .api import api_router

from nsra.research_and_publication import urls as research_and_publication_urls
from nsra.newsletter.urls import urlpatterns as newsletter_urlpatterns
from nsra.news_and_events import urls as news_and_events_urls
from nsra.activity import urls as activity_urls
from nsra.stats import urls as stats_urls

from .views import unauthorized

from wagtail.core import views
views.serve.csrf_exempt = True

handler404 = 'nsra.views.handle404'
handler403 = 'nsra.views.handle403'
handler400 = 'nsra.views.handle400'
handler500 = 'nsra.views.handle500'

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    re_path(r'site-search-x01-csd-12', search_views.search, name='search'),
    path('api/v2/', api_router.urls),

    path('mail/', include(newsletter_urlpatterns), name='birdsong'),
    path('__debug__/', include('debug_toolbar.urls')),
    path('statistics/accidents/', include(stats_urls), name='mycharts'),

    path('401/', unauthorized, name='unauthorized'),

    path('', include(activity_urls), name='activity'),
    path('', include(news_and_events_urls), name='news_and_events'),
    path('', include(research_and_publication_urls), name='research_and_publications'),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

nsra/blog/models.py
from django.db import models
from taggit.models import TaggedItemBase
from wagtail.core.fields import RichTextField
from wagtail.core.models import Page, Orderable
from modelcluster.contrib.taggit import ClusterTaggableManager
from modelcluster.fields import ParentalKey, ParentalManyToManyField
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.snippets.models import register_snippet
from rest_framework.fields import DateField
from wagtail.search import index
from wagtail.api import APIField
from django import forms

class BlogIndexPage(Page):
    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname="full")
    ]

    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super().get_context(request)
        blogpages = self.get_children().live().order_by('-first_published_at')
        context['blogpages'] = blogpages
        return context

class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey(
        'blog.BlogPage',
        related_name='tagged_items',
        on_delete=models.CASCADE
    )

class BlogPage(Page):
    date = models.DateField("Post date")
    intro = models.CharField(max_length=250)
    body = RichTextField(blank=True)
    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    categories = ParentalManyToManyField('blog.BlogCategory', blank=True)

    def main_image(self):
        gallery_item = self.gallery_images.first()
        if gallery_item:
            return gallery_item.image
        else:
            return None

    search_fields = Page.search_fields + [
        index.SearchField('intro'),
        index.SearchField('body'),
    ]

    content_panels = Page.content_panels + [
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('tags'),
            FieldPanel('categories', widget=forms.CheckboxSelectMultiple)
        ], heading="Blog information"),
        FieldPanel('intro'),
        FieldPanel('body', classname="full"),
        InlinePanel('gallery_images', label="Gallery images"),
    ]

    api_fields = [
        # Date in ISO8601 format (the default)
        APIField('published_date'),
        # Change the format of the published_date field to "Thursday 06 April 2017"
        # A separate published_date_display field with a different format
        APIField('published_date_display', serializer=DateField(format='%A $d %B %Y', source='published_date')), 
        APIField('body'),
    ]

class BlogPageGalleryImage(Orderable):
    page = ParentalKey('blog.BlogPage', on_delete=models.CASCADE, related_name='gallery_images')
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )
    caption = models.CharField(blank=True, max_length=250)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]


class BlogTagIndexPage(Page):

    def get_context(self, request):

        # Filter by tag
        tag = request.GET.get('tag')
        blogpages = BlogPage.objects.filter(tags__name=tag)

        # Update template context
        context = super().get_context(request)
        context['blogpages'] = blogpages
        return context

@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(max_length=255)
    icon = models.ForeignKey(
        'wagtailimages.Image', null=True, blank=True,
        on_delete=models.SET_NULL, related_name='+'
    )

    panels = [
        FieldPanel('name'),
        ImageChooserPanel('icon'),
    ]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'blog categories'

nsra/executive/models.py
from django.db import models
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, MultiFieldPanel
from wagtail.snippets.models import register_snippet
from nsra.base.models import BaseModel

@register_snippet
class Executive(BaseModel):
    name = models.CharField(max_length=1000)
    position = models.CharField(max_length=255)
    featured = models.BooleanField(default=False)
    image = models.ForeignKey(
        'wagtailimages.Image', on_delete=models.CASCADE, related_name='+'
    )

    email = models.EmailField(max_length=1000, blank=True, null=True)
    twitter = models.URLField(max_length=10000, blank=True, null=True)
    facebook = models.URLField(max_length=10000, blank=True, null=True)
    instagram = models.URLField(max_length=10000, blank=True, null=True)
    linked_in = models.URLField(max_length=10000, blank=True, null=True)
    pinterest = models.URLField(max_length=10000, blank=True, null=True)

    panels = [
        MultiFieldPanel([
            FieldPanel('name'),
            FieldPanel('position'),
            FieldPanel('featured'),
            ImageChooserPanel('image'),
        ], heading="Executive Information"),
        MultiFieldPanel([
            FieldPanel('email'),
            FieldPanel('twitter'),
            FieldPanel('facebook'),
            FieldPanel('instagram'),
            FieldPanel('linked_in'),
            FieldPanel('pinterest'),
        ], heading="Social Links")
    ]

    def __str__(self):
        return self.name

nsra/newsletter/forms.py
from django import forms
from birdsong.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("email",)

nsra/stats/forms.py
from django import forms


class geo_data(forms.Form):
    date_from = forms.CharField()
    date_to = forms.CharField()
    region = forms.CharField()


class chart_data(forms.Form):
    date_from = forms.CharField()
    date_to = forms.CharField()
    region = forms.CharField()
    category = forms.CharField()
    specific = forms.CharField()


class time_series(forms.Form):
    option = forms.CharField()

nsra/activity/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import ActivityCategory, ActivityIndexPage
from django.views.decorators.csrf import csrf_exempt
from django.http import request, JsonResponse
from rest_framework.response import Response
from django.core import serializers

import json 

def get_page(qs, page=1, size=12):
    paginator = Paginator(qs, size)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(paginator.num_pages)
    return pages

@csrf_exempt
def categorized_page(request, category=None, page=1):

    activities = ActivityCategory.objects.get(pk=category).activities.live() 
    page = get_page(activities, page, ActivityIndexPage.gp_pg_size)

    data = {
        'number': page.number,
        'has_next': page.has_next(),
        'has_previous': page.has_previous(),
        'activities':[
            {
                'url':obj.url,
                'headline': obj.headline,
                # 'summary_title': obj.summary_title
                'summary': '',
                'image': obj.main_image().get_rendition('original').url if obj.main_image() else '',
            } for obj in page
        ]
    }

    return JsonResponse({"data": data})

    # 'count', 'end_index', 'has_next', 'has_other_pages', 'has_previous', 'index', 'next_page_number', 'number', 'object_list', 'paginator', 'previous_page_number', 'start_index'
    # image.get_rendition('original')
    # image.get_rendition('fill-320x200')
    # https://groups.google.com/g/wagtail/c/AAARvKmZ8S4

nsra/news_and_events/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import NewsPage, EventPage, NewsEventsIndexPage
from django.views.decorators.csrf import csrf_exempt
from django.http import request, JsonResponse
from django.core import serializers
import json, datetime

def get_page(qs, page=1, size=12):
    paginator = Paginator(qs, size)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(paginator.num_pages)
    return pages

def get_parent(id):
    return NewsEventsIndexPage.objects.get(pk=id)

@csrf_exempt
def get_news(request, parent, sort='descending', page=1):

    sorting = '-first_published_at' if sort=='descending' else 'first_published_at'
    news = NewsPage.objects.filter().live().descendant_of(get_parent(parent)).order_by(sorting)
    page = get_page(news, page, NewsEventsIndexPage.news_pg_size)

    data = {
        'number': page.number,
        'has_next': page.has_next(),
        'has_previous': page.has_previous(),
        'objects':[
            {
                'url':obj.url,
                'headline': obj.headline,
                'image':  obj.main_image().get_rendition('original').url if obj.main_image() else "",
                'date': obj.date
            } for obj in page
        ]
    }

    return JsonResponse({"data": data})

@csrf_exempt
def get_past_events(request, parent, sort='descending', page=1):
    sorting = '-first_published_at' if sort=='descending' else 'first_published_at'
    events = EventPage.objects.filter(date_time__lt=datetime.datetime.now()).live().descendant_of(get_parent(parent)).order_by(sorting)
    page = get_page(events, page, NewsEventsIndexPage.past_event_pg_size)
    
    data = {
        'number': page.number,
        'has_next': page.has_next(),
        'has_previous': page.has_previous(),
        'objects':[
            {
                'url':obj.url,
                'headline': obj.headline,
                'image':  obj.main_image().get_rendition('original').url if obj.main_image() else "",
                'date': obj.date_time
            } for obj in page
        ]
    }

    return JsonResponse({"data": data})

nsra/newsletter/views.py
import json 
from .forms import ContactForm
from birdsong.models import Contact
from django.http import request, JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def subscribe(request):
    if request.method == "POST":
        data = json.loads(request.body.decode('utf-8'))
        form = ContactForm(data)
        if form.is_valid():
            Contact.objects.get_or_create(email=form.cleaned_data["email"])
            return JsonResponse({"success": True})
        return JsonResponse({"success": False})

nsra/research_and_publication/views.py
from .models import ResearchPage, PublicationPage, ResearchCategory, PublicationCategory, ResearchPublicationIndexPage
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.http import request, JsonResponse
from django.core import serializers
import json, datetime

def get_page(qs, page=1, size=12):
    paginator = Paginator(qs, size)
    try:
        pages = paginator.page(page)
    except PageNotAnInteger:
        pages = paginator.page(1)
    except EmptyPage:
        pages = paginator.page(paginator.num_pages)
    return pages

def get_parent(id):
    return ResearchPublicationIndexPage.objects.get(pk=id)

@csrf_exempt
def get_research(request, parent, category=0, sort='descending', page=1):

    category = int(category)
    sorting = '-first_published_at' if sort=='descending' else 'first_published_at'
    research = ResearchPage.objects.filter().live().descendant_of(get_parent(parent)).order_by(sorting)
    if category:
        research = ResearchCategory.objects.get(pk=category).research.live().descendant_of(get_parent(parent)).order_by(sorting)
    page = get_page(research, page, ResearchPublicationIndexPage.research_pg_size)

    data = {
        'number': page.number,
        'has_next': page.has_next(),
        'has_previous': page.has_previous(),
        'objects':[
            {
                'url':obj.url,
                'headline': obj.headline,
                'image':  obj.main_image().get_rendition('original').url if obj.main_image() else "",
            } for obj in page
        ]
    }

    return JsonResponse({"data": data})

@csrf_exempt
def get_publication(request, parent, category=0, sort='descending', page=1):
    
    category = int(category)
    sorting = '-first_published_at' if sort=='descending' else 'first_published_at'
    publications = PublicationPage.objects.filter().live().descendant_of(get_parent(parent)).order_by(sorting)
    if category:
        publications = PublicationCategory.objects.get(pk=category).research.live().descendant_of(get_parent(parent)).order_by(sorting)
    page = get_page(publications, page, ResearchPublicationIndexPage.publication_pg_size)
    
    data = {
        'number': page.number,
        'has_next': page.has_next(),
        'has_previous': page.has_previous(),
        'objects':[
            {
                'url':obj.url,
                'headline': obj.headline,
                'image':  obj.main_image().get_rendition('original').url if obj.main_image() else "",
            } for obj in page
        ]
    }

    return JsonResponse({"data": data})

nsra/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.core.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query).annotate_score("_score")
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

nsra/templates/stats/charts/FCE.html
{%extends 'stats/charts/index.html'%}
 {% load static %}
 {%block content%}
<div class="urban1 ntf">
  <h5>Changes in National Traffic Fatality Indices</h5>
  <canvas id="FCE" height="120vh"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/FCE.js' %}"></script>
{%endblock%}

nsra/templates/stats/charts/NTCC.html
{%extends 'stats/charts/index.html'%}
{% load static %}

{% block content %}
<div class="container-3">
  <div class="urban1">
    <h5>Casualties</h5>
    <canvas id="nttcc"></canvas>
  </div>
  <div class="urban1">
    <h5>Fatalities</h5>
    <canvas id="nttcc2"></canvas>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/nttcc.js' %}"></script>
{% endblock %}

nsra/templates/stats/charts/NTF.html
{%extends 'stats/charts/index.html'%}
{% load static %}
 
{%block content%}

  <div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false" style="width: 100%;">
      <h5 >Annual Distributions</h5>
    </a>

    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="width: 100%;">
      <li><a class="active" href="{% url 'stats:NTF' %}">Changes in National Traffic Fatality Indices</a><hr></li>
      <li><a href="{% url 'stats:NTCC' %}">National Trends in Traffic Casualties & Crashes</a><hr></li>
      <li><a href="{% url 'stats:age_group'%}">Fatalities & Casualties (Age groups)</a><hr></li>
      <li> <a href="{% url 'stats:FCE' %}">Fatalities & Casualties (Environment)</a><hr></li>
      <li> <a href="{% url 'stats:gender' %}">Fatalities & Casualties (sex)</a><hr></li>
      <li>  <a href="{% url 'stats:UNF' %}">Urban and nonUrban Fatalities</a><hr></li>
      <li><a href="{% url 'stats:UNC' %}">Urban and nonUrban Casualties</a><hr></li>
      <li><a href="{% url 'stats:vehicles' %}"> Vehicles Involved in Crashes</a><hr></li>
      <li></li>
    </ul>
  
  </div>


  <div class="urban1 ntf" style="width: 100%; height:100%; margin-top: 40px;">
    <h5>Changes in National Traffic Fatality Indices</h5>
    <canvas id="byRoad" height="120vh"></canvas>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <script src="{% static 'js/chartTime.js' %}"></script>
{%endblock%}

{% block extra_js %}
<script>
</script>
{%endblock%}

nsra/templates/stats/charts/UNC.html
{%extends 'stats/charts/index.html'%}
{% load static %} 
{%block content%}
<h5 style="text-align: center;">Casualties (Urban & Non-Urban</h5>
<div class="container-3">
  <div class="urban1">
    <h5>Urban</h5>
    <canvas id="unc"></canvas>
  </div>
  <div class="urban1">
    <h5>Non-Urban</h5>
    <canvas id="unc2"></canvas>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/UNC.js' %}"></script>
{%endblock%}

nsra/templates/stats/charts/UNF.html
{%extends 'stats/charts/index.html'%}
{% load static %}
{%block content%}
<h5 style="text-align: center;">Fatalities (Urban & Non-Urban</h5>
<div class="container-3">
  <div class="urban1">
    <h5>Urban</h5>
    <canvas id="urbanFatalities"></canvas>
  </div>
  <div class="urban1">
    <h5>Non-Urban</h5>
    <canvas id="nonUrbanFatal"></canvas>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/UNF.js' %}"></script>
{%endblock%}

nsra/templates/stats/charts/age_group.html
{%extends 'stats/charts/index.html'%}
{% load static %}
{%block content%}
<div class="container-3">
  <div class="urban1">
    <h5>Casualties by age Groups</h5>
    <canvas id="ageGroup"></canvas>
  </div>
  <div class="urban1">
    <h5>Fatalities by age Groups</h5>
    <canvas id="ageGroup2"></canvas>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/age_group.js' %}"></script>
{%endblock%}

nsra/templates/stats/charts/casualties.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Data representation</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/charts.css' %}" />
  </head>

  <body>
    <!-- main page -->
    <div class="main-page">
      <div class="top">
        <div class="row">
          <div class="col-4"><h3>GHANA NRSA</h3></div>
          <div class="col-4"></div>
          <div class="col-4">
            <div class="flex-box">
              <a href="{% url 'Data:index' %}">
                <button class="btn" type="button">Geo view</button>
              </a>
              <div class="dropdown">
                <button
                  class="btn dropdown-toggle"
                  type="button"
                  data-toggle="dropdown"
                >
                  Sort By: <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                  <li><a href="#">Fatalities</a></li>
                  <hr class="hr" />
                  <li><a href="#">Casualties</a></li>
                  <hr class="hr" />
                  <li><a  href="{% url 'Data:chart' %}">Go to main chart</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
     <div class="Previous">
      <a href="{% url 'stats:time_main' %}"><button>Go to Prevous Menu</button></a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/chartTime.js' %}"></script>

  </body>
</html>

nsra/templates/stats/charts/charts.html
{%extends 'stats/charts/index.html'%}
{% load static %}

{% block content %}
 
<section>

        <div class="jumbotron-fluid">
          <h3>Total Cases recorded in 2021</h3>
          <hr>
          <div class="container">
              <canvas id="Year" width="20%" height="5%"></canvas>
          </div>
        </div>

        <div style="width: 100%; height:auto; flex-direction:row; flex-wrap: wrap  ">
          <div>
            <h5 style="text-decoration: underline;">Regional cases</h5>
            <canvas id="RegionsN"  width="100%" height="30%"></canvas>
          </div>
          <div>
            <h5 style="text-decoration: underline;margin-top: 40px">Other cases (VEHICLES)</h5>
             <canvas id="vehiclesN" width="100%" height="30%"></canvas>
          </div>
          <div>
            <h5 style="text-decoration: underline;margin-top: 40px">Pedestrian Cases</h5>
            <canvas id="pedestrian"  width="100%" height="30%"></canvas>
          </div>
        </div>

      </div>
      </div>

      <script src="{% static 'js/charts.js' %}"></script>
</section>
{% endblock content %}

nsra/templates/stats/charts/time_main.html
{% extends "base.html" %}
{% load static %}
{% load wagtailcore_tags %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
/>
<link rel="stylesheet" href="{% static 'css/charts.css' %}" />

{% endblock  %}

{%block content%}

<section>
<!-- main page -->
<!-- <div class="main-page">
  <div class="top">
    <div class="row">
      <div class="col-4"></div>
      <div class="col-4">
        <div class="flex-box">
          <a href="{% url 'stats:index' %}">
            <button class="btn" type="button">Geo view</button>
          </a>
           <a href="{% url 'stats:chart' %}">
            <button class="btn Bar" type="button">Geo BarChart</button>
          </a>
        </div>
      </div>
    </div>
  </div>
</div> -->

<!-- <div class="sidebar">
<h4 style="padding: 5px 0; text-decoration: underline; text-align:center; font-family: serif;">Annual Distributions</h4>
<a class="active" href="{% url 'stats:NTF' %}">Changes in National Traffic Fatality Indices</a><hr>
 <a href="{% url 'stats:NTCC' %}">National Trends in Traffic Casualties & Crashes</a><hr>
<a href="{% url 'stats:age_group'%}">Fatalities & Casualties (Age groups)</a><hr>
<a href="{% url 'stats:FCE' %}">Fatalities & Casualties (Environment)</a><hr>
<a href="{% url 'stats:gender' %}">Fatalities & Casualties (sex)</a><hr>
<a href="{% url 'stats:UNF' %}">Urban and nonUrban Fatalities</a><hr>
<a href="{% url 'stats:UNC' %}">Urban and nonUrban Casualties</a><hr>
<a href="{% url 'stats:vehicles' %}"> Vehicles Involved in Crashes</a><hr>

  {% comment %} <a href="#">Casualties by Road User Class</a><hr>
<a href="#">Casualties by Road User Class</a><hr> {% endcomment %}
</div> -->

<!-- 
<div class="lineChart">
  <h4>CRASHES AND FATALITIES FROM 1991-2020</h4>
  {% comment %} <div class="row2"> {% endcomment %}
    {%block chart_content%}
    {%endblock%}
 <div class="Previous">
  <a href="{% url 'stats:chart' %}"><button>Go to Bar Charts</button></a>
</div>
</div> -->

</section>
 <script>

</script>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock%}

nsra/templates/stats/charts/vehicles.html
{%extends 'stats/charts/index.html'%}
{% load static %}
{%block content%}
<div class="urban1 ntf">
 <h5>Vehicles involved in the Crashes </h5>
 <canvas id="Vehicles" height="120vh"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="{% static 'js/Vehicle.js' %}"></script>
{%endblock%}